use crate::config::Config;
use crate::sandbox;
use crate::server;
use crate::ssh;
use std::error::Error;
use std::process::Command;
use tempfile::NamedTempFile;

fn service_name(package_name: &str) -> String {
  format!("{package_name}.service")
}

fn generate_service_file(
  bin_name: &str,
  remote_path: &str,
  config: &Config,
) -> String {
  let bin_path = format!("{remote_path}/target/release/{bin_name}");

  let mut env_lines = String::new();
  for (k, v) in &config.sandbox.env {
    let escaped = v.replace('\\', "\\\\").replace('"', "\\\"");
    env_lines.push_str(&format!("Environment=\"{k}={escaped}\"\n"));
  }

  format!(
    "# Auto-generated by rcargo. Do not edit manually.\n\
     \n\
     [Unit]\n\
     Description={bin_name}\n\
     After=network.target\n\
     \n\
     [Service]\n\
     Type=simple\n\
     ExecStart={bin_path}\n\
     WorkingDirectory={remote_path}\n\
     {env_lines}\
     Restart=on-failure\n\
     RestartSec=5\n\
     \n\
     [Install]\n\
     WantedBy=default.target\n"
  )
}

pub fn deploy(
  config: &Config,
  remote_path: &str,
  home: &str,
  bin_name: &str,
  debug: bool,
) -> Result<(), Box<dyn Error>> {
  let host = &config.target;
  let svc = service_name(bin_name);

  // Stop any existing process (PID file or systemd service)
  let _ = server::stop_server(host, remote_path, bin_name);

  let shim_path = crate::shim::sync_only(config, remote_path, home)?;

  server::run_hooks(config, remote_path, debug)?;

  println!("Building on remote...");
  let cmd = sandbox::inner_cmd(config, remote_path);
  match crate::shim::run_only(
    config,
    remote_path,
    home,
    &shim_path,
    &cmd,
    debug,
  ) {
    Ok(0) => {}
    Ok(code) => {
      return Err(
        format!("Remote build failed with exit code: {code}").into(),
      );
    }
    Err(e) => {
      return Err(format!("Remote build failed: {e}").into());
    }
  }

  println!("Configuring systemd service...");
  let service_content =
    generate_service_file(bin_name, remote_path, config);
  let service_dir = format!("{home}/.config/systemd/user");
  let service_path = format!("{service_dir}/{svc}");

  ssh::ssh_capture(
    host,
    &format!("mkdir -p {}", ssh::shell_quote(&service_dir)),
  )?;

  // Write the service file via scp to avoid heredoc
  // delimiter collision issues with ssh piping.
  let tmp = NamedTempFile::new()?;
  std::fs::write(tmp.path(), &service_content)?;
  let scp_status = Command::new("scp")
    .args([
      "-q",
      "-o",
      "BatchMode=yes",
      tmp.path().to_str().unwrap(),
      &format!("{host}:{service_path}"),
    ])
    .status();
  let status =
    scp_status.map_err(|e| format!("failed to run scp: {e}"))?;
  if !status.success() {
    return Err(
      format!(
        "scp failed with exit code: {}",
        status.code().unwrap_or(-1)
      )
      .into(),
    );
  }

  ssh::ssh_run(host, "systemctl --user daemon-reload")?;
  ssh::ssh_run(host, &format!("systemctl --user enable {svc}"))?;
  ssh::ssh_run(host, &format!("systemctl --user start {svc}"))?;

  println!("Deployed {bin_name} as systemd user service");
  Ok(())
}

pub fn undeploy(
  config: &Config,
  remote_path: &str,
  home: &str,
  bin_name: &str,
) -> Result<(), Box<dyn Error>> {
  let host = &config.target;
  let svc = service_name(bin_name);

  let _ = ssh::ssh_run(host, &format!("systemctl --user stop {svc}"));
  let _ =
    ssh::ssh_run(host, &format!("systemctl --user disable {svc}"));

  let service_path = format!("{home}/.config/systemd/user/{svc}");
  let _ = ssh::ssh_run(
    host,
    &format!("rm -f {}", ssh::shell_quote(&service_path)),
  );

  ssh::ssh_run(host, "systemctl --user daemon-reload")?;

  let bin_path = format!("{remote_path}/target/release/{bin_name}");
  let _ = ssh::ssh_run(
    host,
    &format!("rm -f {}", ssh::shell_quote(&bin_path)),
  );

  println!("Undeployed {bin_name}");
  Ok(())
}
